name: folha_pagamento_itps
description: Sistema de calculo de convenio ITPS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Banco de dados local para Windows
  sqflite_common_ffi: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.8.3
  # Gerenciamento de estado simples
  provider: ^6.0.5
  # Formatação de moeda (R$)
  intl: ^0.19.0
  excel: ^4.0.2
  file_selector: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # CORRIGIDO AQUI (Faltava o numero final)
  flutter_launcher_icons: ^0.13.1

# Configuração dos Ícones
flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/images/logo.png"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48

flutter:
  uses-material-design: true

  # CORRIGIDA A INDENTAÇÃO (Espaços são vitais no YAML)
  assets:
    - assets/images/